### ISSUE TITLE
Client类sendRequest方法accessToken拼接有误

### ISSUE THREAD

**Issue by qq1052663897** [handsomegyr/jinritemai#1]
public function sendRequest(\Jinritemai\Request\Base $request, array $options = array())
	{
		$param_json = $request->getParams();
		$apiMethodName = $request->getApiMethodName();
		$params = array();
		$params['method'] = str_replace('/', '.', $apiMethodName);
		$params['app_key'] = $this->getAppId();
		$needToken = $request->isNeedAccessToken();
		if ($needToken) {
			$params['access_token'] = $this->getAccessToken();
		}
		// 无（注意：param_json请按照空对象 "{}" 传递）
		if (empty($param_json)) {
			$params['param_json'] = '{}';
		} else {
			$params['param_json'] = \json_encode($param_json);
		}
		$params['timestamp'] = date("Y-m-d H:i:s", time());
		$params['v'] = $this->_v;
		$params['sign'] = $this->signature($params);
		$headers = array();
		$rst = $this->getRequest()->post($this->_url . $apiMethodName, $params, $headers);
		return $this->rst($rst);
	}

其中
if ($needToken) {
			$params['access_token'] = $this->getAccessToken();
		}
应该放到拼接sign方法之后，否则会将accessToke拼到sign里，最终会返回error_no:11 sign 错误

**Comment by handsomegyr** [comment]
多谢 已经按照你的方案解决该问题
